import type { Garment } from "@/domain/garment";

export const mockGarments: readonly Garment[] = [
  {
    id: "atlas-overcoat",
    brand: "Atlas Studio",
    name: "Boxy Wool Overcoat",
    price: { amountCents: 24800, currency: "USD" },
    description: "A structured wool overcoat with a clean shoulder and a long, easy line.",
    videoUrl: "/clips/atlas-overcoat.mp4",
    posterUrl: "/clips/atlas-overcoat.jpg",
  },
  {
    id: "northline-jacket",
    brand: "Northline",
    name: "Washed Indigo Jacket",
    price: { amountCents: 18900, currency: "USD" },
    description: "Broken-in indigo cotton with a cropped workwear cut.",
    videoUrl: "/clips/northline-jacket.mp4",
    posterUrl: "/clips/northline-jacket.jpg",
  },
  {
    id: "lumen-knit",
    brand: "Lumen",
    name: "Merino Crew Knit",
    price: { amountCents: 12800, currency: "USD" },
    description: "Fine merino crewneck that holds its shape without feeling stiff.",
    videoUrl: "/clips/lumen-knit.mp4",
    posterUrl: "/clips/lumen-knit.jpg",
  },
  {
    id: "harbor-trouser",
    brand: "Harbor & Co",
    name: "Pleated Wide Trouser",
    price: { amountCents: 16400, currency: "USD" },
    description: "Soft pleated trousers with a full leg and a tailored waist.",
    videoUrl: "/clips/harbor-trouser.mp4",
    posterUrl: "/clips/harbor-trouser.jpg",
  },
  {
    id: "solace-dress",
    brand: "Solace",
    name: "Silk Slip Dress",
    price: { amountCents: 21000, currency: "USD" },
    description: "Bias-cut slip with a quiet drape and a square neckline.",
    videoUrl: "/clips/solace-dress.mp4",
    posterUrl: "/clips/solace-dress.jpg",
  },
  {
    id: "ridge-shirt",
    brand: "Ridge",
    name: "Poplin Shirt",
    price: { amountCents: 9800, currency: "USD" },
    description: "Crisp poplin shirt with a relaxed body and a precise collar.",
    videoUrl: "/clips/ridge-shirt.mp4",
    posterUrl: "/clips/ridge-shirt.jpg",
  },
  {
    id: "ember-cardigan",
    brand: "Ember",
    name: "Cashmere Cardigan",
    price: { amountCents: 27600, currency: "USD" },
    description: "Lightweight cashmere cardigan meant to be worn open over everything.",
    videoUrl: "/clips/ember-cardigan.mp4",
    posterUrl: "/clips/ember-cardigan.jpg",
  },
  {
    id: "volt-tee",
    brand: "Volt",
    name: "Heavyweight Tee",
    price: { amountCents: 6400, currency: "USD" },
    description: "Heavy cotton tee with a set-in sleeve and a short, boxy hem.",
    videoUrl: "/clips/volt-tee.mp4",
    posterUrl: "/clips/volt-tee.jpg",
  },
];
